//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-325 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.17 at 08:35:20 PM CEST 
//


package nl.gridshore.schema.myservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.gridshore.schema.myservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MyServiceResponse_QNAME = new QName("http://www.gridshore.nl/schema/myservice", "MyServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.gridshore.schema.myservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyServiceResponseType.Data }
     * 
     */
    public MyServiceResponseType.Data createMyServiceResponseTypeData() {
        return new MyServiceResponseType.Data();
    }

    /**
     * Create an instance of {@link MyServiceResponseType }
     * 
     */
    public MyServiceResponseType createMyServiceResponseType() {
        return new MyServiceResponseType();
    }

    /**
     * Create an instance of {@link MyServiceRequest }
     * 
     */
    public MyServiceRequest createMyServiceRequest() {
        return new MyServiceRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gridshore.nl/schema/myservice", name = "MyServiceResponse")
    public JAXBElement<MyServiceResponseType> createMyServiceResponse(MyServiceResponseType value) {
        return new JAXBElement<MyServiceResponseType>(_MyServiceResponse_QNAME, MyServiceResponseType.class, null, value);
    }

}
